--------------------------BUILT-IN FUNCTIONS---------------------------------

the most useful in machine learning
- abs()
- round()
- max(list) / min / len / sum / all / any 

fonction de converion de types
- type()
- str(x) / int 
- tuple(list) / list 

interaction with user
- input()
- int(input("***"))

- format(x)
    - espacialy with neural network 
    
- open(file, mode)
- use differts methods on object of open (write, read, close...)
- with open () as f: f.read() #without closing

In [1]:
# absolute value 
x= -3
abs(x)

3

In [3]:
#most near value
x = 3.4
y = 3.6
print(round(x))
print(round(y))

3
4


In [7]:
liste_1 = [21,34,52,43,56,78,76]
print(max(liste_1))
print(min(liste_1))
print(len(liste_1))
print(sum(liste_1))

78
21
7
360


In [9]:
#return true if all value = True (!=0)
all(liste_1)

True

In [10]:
#return true if at least one value = true 
any(liste_1)

True

# conversion function

In [11]:
#check the type of variables
x, y, z = 7, True, 'word'
print(type(x), type(y), type(z))

<class 'int'> <class 'bool'> <class 'str'>


In [19]:
str(x) #from int to string


'7'

In [20]:
str(y)

'True'

In [22]:
dico = {'banane':40,
       'pomme':34,
       'kiwi':89,
       'orange':32}

list(dico.keys())

['banane', 'pomme', 'kiwi', 'orange']

In [23]:
list(dico.values())

[40, 34, 89, 32]

In [26]:
person = dict(name = "Alex", age = 18, address = "Paris")
print(person)

{'name': 'Alex', 'age': 18, 'address': 'Paris'}


In [27]:
tuple(liste_1)

(21, 34, 52, 43, 56, 78, 76)

## user interaction

In [28]:
input()

hi how are you


'hi how are you'

In [30]:
name = input("Enter your name please : ")
age = int(input("Enter your age please : "))

Enter your name please : toto
Enter your age please : 30


In [37]:
import numpy as np
neuron = {'w0':np.random.randn(2,5),
         'w1':np.random.randn(2,3),
         'w2':np.random.randn(2,4)}

In [40]:
#accer au valeurs 
for i in range(3):
    print("couche",i)
    print(neuron["w{}".format(i)])

couche 0
[[ 0.28199188  0.35530642  0.82120986  0.02814573 -0.29360345]
 [ 1.35333209  0.33783131 -0.18093895 -0.56942028 -1.06840272]]
couche 1
[[ 0.43641374  2.00641694 -1.66002601]
 [-0.83011055  1.83324304 -0.28082451]]
couche 2
[[-0.25307193  0.17871562  0.08774189  0.11624396]
 [-0.86391752  3.11198299 -0.32808093 -2.06385721]]


In [43]:
f = open('test.txt', 'w')

In [44]:
f.write("qwertyuiopasdfghjklzxcvbnm")
f.close()

In [45]:
! cat test.txt

qwertyuiopasdfghjklzxcvbnm


In [46]:
f = open('test.txt', 'r')
f.read()

'qwertyuiopasdfghjklzxcvbnm'

In [51]:
#another method
with open("test.txt", "r") as f:
    print(f.read())

qwertyuiopasdfghjklzxcvbnmbonjour


In [56]:
with open("test.txt", "w") as f:
    for i in range(100):
        f.write("{}^2 = {} \n".format(i, i**2))

In [58]:
#! cat test.txt

In [68]:
#stock content of test.txt inside a liste 
f = open('test.txt', 'r')
squares_list = f.read().splitlines()
#readlines() another methode, but display also \n 
f.close()

In [69]:
squares_list

['0^2 = 0 ',
 '1^2 = 1 ',
 '2^2 = 4 ',
 '3^2 = 9 ',
 '4^2 = 16 ',
 '5^2 = 25 ',
 '6^2 = 36 ',
 '7^2 = 49 ',
 '8^2 = 64 ',
 '9^2 = 81 ',
 '10^2 = 100 ',
 '11^2 = 121 ',
 '12^2 = 144 ',
 '13^2 = 169 ',
 '14^2 = 196 ',
 '15^2 = 225 ',
 '16^2 = 256 ',
 '17^2 = 289 ',
 '18^2 = 324 ',
 '19^2 = 361 ',
 '20^2 = 400 ',
 '21^2 = 441 ',
 '22^2 = 484 ',
 '23^2 = 529 ',
 '24^2 = 576 ',
 '25^2 = 625 ',
 '26^2 = 676 ',
 '27^2 = 729 ',
 '28^2 = 784 ',
 '29^2 = 841 ',
 '30^2 = 900 ',
 '31^2 = 961 ',
 '32^2 = 1024 ',
 '33^2 = 1089 ',
 '34^2 = 1156 ',
 '35^2 = 1225 ',
 '36^2 = 1296 ',
 '37^2 = 1369 ',
 '38^2 = 1444 ',
 '39^2 = 1521 ',
 '40^2 = 1600 ',
 '41^2 = 1681 ',
 '42^2 = 1764 ',
 '43^2 = 1849 ',
 '44^2 = 1936 ',
 '45^2 = 2025 ',
 '46^2 = 2116 ',
 '47^2 = 2209 ',
 '48^2 = 2304 ',
 '49^2 = 2401 ',
 '50^2 = 2500 ',
 '51^2 = 2601 ',
 '52^2 = 2704 ',
 '53^2 = 2809 ',
 '54^2 = 2916 ',
 '55^2 = 3025 ',
 '56^2 = 3136 ',
 '57^2 = 3249 ',
 '58^2 = 3364 ',
 '59^2 = 3481 ',
 '60^2 = 3600 ',
 '61^2 = 3721 ',
 '